	with wide_data as  (
			select 
				*
			 from {{ ref('stg_khis_moh_505') }}
	), cross_applied_data as (
     {{ 
		cross_apply_columns('wide_data', 
			[								
				'Bacterial Meningitis +ve H Influenza',
				'Bacterial Meningitis +ve Nm',
				'Bacterial Meningitis +ve Sp',
				'Bacterial Meningitis No CSF',
				'Bacterial Meningitis No Contaminated',
				'Bacterial Meningitis No Tested',			
				'Deaths Due to Malaria <5 yrs, Cases',
				'Deaths Due to Malaria <5 yrs, Deaths',
				'Deaths Due to Malaria >5 yrs, Cases',
				'Deaths Due to Malaria >5 yrs, Deaths', 
				'AEFI <5 yrs, Cases',
				'AEFI <5 yrs, Deaths',
				'AEFI >5 yrs, Cases',
				'AEFI >5 yrs, Deaths',
				'Acute Flaccid Paralysis <5 yrs, Cases',
				'Acute Flaccid Paralysis <5 yrs, Deaths',
				'Acute Flaccid Paralysis >5 yrs, Cases',
				'Acute Flaccid Paralysis >5 yrs, Deaths',
				'Acute Jaundice <5 yrs, Cases',
				'Acute Jaundice <5 yrs, Deaths',
				'Acute Jaundice >5 yrs, Cases',
				'Acute Jaundice >5 yrs, Deaths',
				'Acute Malnutrition <5 yrs, Cases',
				'Acute Malnutrition <5 yrs, Deaths',
				'Acute Malnutrition >5 yrs, Cases',
				'Acute Malnutrition >5 yrs, Deaths',
				'Anthrax <5 yrs, Cases',
				'Anthrax <5 yrs, Deaths',
				'Anthrax >5 yrs, Cases',
				'Anthrax >5 yrs, Deaths',
				'Cholera <5 yrs, Cases',
				'Cholera <5 yrs, Deaths',
				'Cholera >5 yrs, Cases',
				'Cholera >5 yrs, Deaths',
				'Dengue <5 yrs, Cases',
				'Dengue <5 yrs, Deaths',
				'Dengue >5 yrs, Cases',
				'Dengue >5 yrs, Deaths',
				'Dysentery <5 yrs, Cases',
				'Dysentery <5 yrs, Deaths',
				'Dysentery >5 yrs, Cases',
				'Dysentery >5 yrs, Deaths',
				'Guinea Worm Disease <5 yrs, Cases',
				'Guinea Worm Disease <5 yrs, Deaths',
				'Guinea Worm Disease >5 yrs, Cases',
				'Guinea Worm Disease >5 yrs, Deaths',
				'Maternal deaths <5 yrs, Cases',
				'Maternal deaths <5 yrs, Deaths',
				'Maternal deaths >5 yrs, Cases',
				'Maternal deaths >5 yrs, Deaths',
				'Measles <5 yrs, Cases',
				'Measles <5 yrs, Deaths',
				'Measles >5 yrs, Cases',
				'Measles >5 yrs, Deaths',
				'Meningococcal Meningitis <5 yrs, Cases',
				'Meningococcal Meningitis <5 yrs, Deaths',
				'Meningococcal Meningitis >5 yrs, Cases',
				'Meningococcal Meningitis >5 yrs, Deaths',
				'Neonatal Tetanus <5 yrs, Cases',
				'Neonatal Tetanus <5 yrs, Deaths',
				'Neonatal Tetanus >5 yrs, Cases',
				'Neonatal Tetanus >5 yrs, Deaths',
				'Neonatal deaths <5 yrs, Cases',
				'Neonatal deaths <5 yrs, Deaths',
				'Neonatal deaths >5 yrs, Cases',
				'Neonatal deaths >5 yrs, Deaths',
				'Other Viral Haemorrhagic Fevers <5 yrs, Cases',
				'Other Viral Haemorrhagic Fevers <5 yrs, Deaths',
				'Other Viral Haemorrhagic Fevers >5 yrs, Cases',
				'Other Viral Haemorrhagic Fevers >5 yrs, Deaths',
				'Other cases <5 yrs, Cases',
				'Other cases <5 yrs, Deaths',
				'Other cases >5 yrs, Cases',
				'Other cases >5 yrs, Deaths',
				'Plague <5 yrs, Cases',
				'Plague <5 yrs, Deaths',
				'Plague >5 yrs, Cases',
				'Plague >5 yrs, Deaths',
				'Rabies <5 yrs, Cases',
				'Rabies <5 yrs, Deaths',
				'Rabies >5 yrs, Cases',
				'Rabies >5 yrs, Deaths',
				'Rift Valley Fever <5 yrs, Cases',
				'Rift Valley Fever <5 yrs, Deaths',
				'Rift Valley Fever >5 yrs, Cases',
				'Rift Valley Fever >5 yrs, Deaths',
				'SARI (Cluster =3 cases) <5 yrs, Cases',
				'SARI (Cluster =3 cases) <5 yrs, Deaths',
				'SARI (Cluster =3 cases) >5 yrs, Cases',
				'SARI (Cluster =3 cases) >5 yrs, Deaths',
				'Suspected MDR/XDR TB <5 yrs, Cases',
				'Suspected MDR/XDR TB <5 yrs, Deaths',
				'Suspected MDR/XDR TB >5 yrs, Cases',
				'Suspected MDR/XDR TB >5 yrs, Deaths',
				'Suspected Malaria <5 yrs, Cases',
				'Suspected Malaria <5 yrs, Deaths',
				'Suspected Malaria >5 yrs, Cases',
				'Suspected Malaria >5 yrs, Deaths',
				'Typhoid <5 yrs, No. of Tests performed',
				'Typhoid <5 yrs, Positive',
				'Typhoid >5 yrs, No. of Tests performed',
				'Typhoid >5 yrs, Positive',
				'Typhoid <5 yrs, Cases',
				'Typhoid <5 yrs, Deaths',
				'Typhoid >5 yrs, Cases',
				'Typhoid >5 yrs, Deaths',
				'Yellow Fever <5 yrs, Cases',
				'Yellow Fever <5 yrs, Deaths',
				'Yellow Fever >5 yrs, Cases',
				'Yellow Fever >5 yrs, Deaths',
				'Malaria <5 yrs Microscopy Positive',
				'Malaria >5 yrs  Microscopy Positive',
				'Malaria <5 yrs Microscopy Tested',
				'Malaria >5 yrs Microscopy Tested',
				'Malaria <5 yrs mRDT Positive',
				'Malaria >5 yrs mRDT Positive',
				'Malaria <5 yrs mRDT Tested',
				'Malaria >5 yrs  mRDT Tested',
				'CSF -Type Indeterminate',
				'CSF -Typed +ve NmA',
				'CSF -Typed +ve NmB',
				'CSF -Typed +ve NmC',
				'CSF -Typed +ve NmW 135',
				'CSF -Typed +ve NmX',
				'CSF -Typed HiB',
				'Shigella Dysentry Positive <5 yrs',
				'Shigella Dysentry Positive >5 yrs',
				'Shigella DysentryTested <5 yrs',
				'Shigella DysentryTested >5 yrs',
				'Tubercullosis <5 yrs MDR/XDR Positive',
				'Tubercullosis >5 yrs MDR/XDR_ Positive',
				'Tubercullosis <5 yrs MDR/XDR_Tested',
				'Tubercullosis >5 yrs MDR/XDR_Tested',
				'Typhoid Positive <5 yrs',
				'Typhoid Positive >5 yrs',
				'Typhoid Tested <5 yrs',
				'Typhoid Tested >5 yrs'
			]
		)
	}}

	)
	select
		case 
			when column_name like '%<5%' then '< 5 years'
			when column_name like '% >5%' then '>= 5 years'
	    end as age_group,
		Period as period,
		cross_applied_data.county,
		cross_applied_data.sub_county,
	 	cross_applied_data.column_name as indicator,
		cross_applied_data.column_value as indicator_value,
		cast(current_date as date) as load_date
	from cross_applied_data