with raw_krcs as (
    select
        cbs_date::date as cbs_date,
        cbs_date::date as case_date,
        to_char(cbs_date, 'YYYY "W"IW') as epi_week,
        volunteer_id::bigint as volunteer_id,
        alert::text as alert,
        alert_village_id::bigint as alert_village_id,
        project::text as project,
        volunteer_name::text as volunteer_name,
        volunteer_village_id::bigint as volunteer_village_id,
        county::text as county,
        alert_village_name::text as alert_village_name,
        alert_status::boolean as alert_status,
        alert_details::text as alert_details,
        id_mismatch::boolean as id_mismatch,
        confirmed::boolean as confirmed,
        investigated::text as investigated,
        investigation_date::date as investigation_date,
        outcome::text as outcome,
        action_red_cross::text as action_red_cross,
        action_government::text as action_government,
        supervisor_name::text as supervisor_name,
        supervisor_phone::text as supervisor_phone
    from {{ source('central_raw_krcs', 'cbs') }}
)

select
    cbs_date,
    case_date,
    epi_week,
    volunteer_id,
    alert,
    alert_village_id,
    project,
    volunteer_name,
    volunteer_village_id,
    county || ' County' AS county,
    alert_village_name,
    alert_status,
    alert_details,
    id_mismatch,
    confirmed,
    investigated,
    investigation_date,
    outcome,
    action_red_cross,
    action_government,
    supervisor_name,
    supervisor_phone
from raw_krcs
