select 
   	date_start::date as date_start,
    date_end:: date as date_end,
    substring(county from '^(.*?) County') as county,
    substring(subcounty from '^(.*?) Sub County') as subcounty,
    unit_id,
    unit_name,
    unit_createdat,
    unit_updatedat,
    unit_code,
    unit_uid,
    unit_state,
    unit_type,
    hebs_signals_reported,
    hebs_signals_verified,
    hebs_signals_verified_true,
    hebs_signals_risk_assessed,
    hebs_signals_responded,
    hebs_signals_to_be_escalated,
    hebs_signals_escalated,
    cebs_signals_reported,
    cebs_signals_verified,
    cebs_signals_verified_true,
    cebs_signals_risk_assessed,
    cebs_signals_responded,
    cebs_signals_to_be_escalated,
    cebs_signals_escalated,
    chvs_registered,
    chvs_reporting,
    chas_registered,
    chas_verifying,
    hcws_registered,
    hcws_reporting,
    sfps_registered,
    sfps_verifying,
    created_at,
    updated_at,
    deleted_at
 from{{ source('central_raw_mdharura', 'mdharura_ebs_aggregate') }} 
 