select
    cbs_date,
    case_date,
    epi_week,
    volunteer_id,
    alert,
    alert_village_id,
    project,
    volunteer_name,
    volunteer_village_id,
    county,
    alert_village_name,
    alert_status,
    alert_details,
    id_mismatch,
    confirmed,
    investigated,
    investigation_date,
    outcome,
    action_red_cross,
    action_government,
    supervisor_name,
    supervisor_phone,
    current_date AS load_date
from {{ ref('stg_krcs_cbs') }}
